export   const escuelas =[
    {
        "id": "95025c1b-e976-4bb6-96ca-d6e8f770afcb",
        "title": "Foreign exchange",
        "image": "school/foreign_ex.png",
        "color": "#74E69C",
        "cl_backg": "#0B120B",
        "cl_border": "#253A2A",
        "bacground_img": "school/bg-card-foreing.jpg",
        "background_full": "school/foreing_fl.png",
        "bg_acad": "school/bg-acad-foreing-fex.png",
        "bg_btns": "school/bg-btns-menu-foreing-fex.png",
        "bg_calendar": "school/bg-calendar-foreing-fex.png",
        "bg_educ": "school/bg-educ-foreing-fex.png",
        "bg_live": "school/bg-live-foreing-fex.png",
        "bg_commun": "school/bg-modu-commun-foreing-fex.png",
        "bg_pro": "school/bg-pro-foreing-fex.png",
        "bg_btn_follow": "school/bg-btn-follow-fex.png",
        "bg_btn_send": "school/bg-btn-send-fex.png",
        "bg_carrousel": "school/bg-btns-carrousel-fex.png",
        "bg_comment_edu": "school/bg-comment-educator-fex.png",
        "bg_favorite_video": "school/bg-favorite-videos-fex.png",
        "bg_stream_chat": "school/bg-stream-chat-fex.png",
        "bg_comment_preg": "school/bg-comment_preg-fex.png",
        "bg_progress": "school/bg-progress-fex.png",
        "bg_send_preg": "school/btn-send-fex.png",
        "bg_btn_tap": "school/tab-foreing.png",
        "cl_text": "#0B120B",
        "created_at": "2024-01-18T11:50:21.529Z",
        "state": "A"
    },
    {
        "id": "ec4b3a61-4975-400e-bfee-7ed5ce9fd9ef",
        "title": "Stocks and crypto",
        "image": "school/stocks_cryp.png",
        "color": "#EBD75F",
        "cl_backg": " #131001",
        "cl_border": "#4E4512",
        "bacground_img": "school/bg-card-crypto.png",
        "background_full": "school/stocksandcryptos_fl.png",
        "bg_acad": "school/bg-acad-crypto-stk.png",
        "bg_btns": "school/bg-btns-menu-crypto-stk.png",
        "bg_calendar": "school/bg-calendar-crypto-stk.png",
        "bg_educ": "school/bg-educ-crypto-stk.png",
        "bg_live": "school/bg-live-crypto-stk.png",
        "bg_commun": "school/bg-modu-commun-crypto-stk.png",
        "bg_pro": "school/bg-pro-crypto-stk.png",
        "bg_btn_follow": "school/bg-btn-follow-stk.png",
        "bg_btn_send": "school/bg-btn-send-stk.png",
        "bg_carrousel": "school/bg-btns-carrousel-stk.png",
        "bg_comment_edu": "school/bg-comment-educator-stk.png",
        "bg_favorite_video": "school/bg-favorite-videos-stk.png",
        "bg_stream_chat": "school/bg-stream-chat-stk.png",
        "bg_comment_preg": "school/bg-comment-stk.png",
        "bg_progress": "school/bg-progress-stk.png",
        "bg_send_preg": "school/btn-send-stk.png",
        "bg_btn_tap": "school/tab-crypto.png",
        "cl_text": "#131001",
        "created_at": "2024-01-18T11:50:21.638Z",
        "state": "A"
    },
    {
        "id": "66febe3a-9849-495a-b7da-aace14720f47",
        "title": "E-commerce",
        "image": "school/e_commerce.png",
        "color": "#C80813",
        "cl_backg": "#200203",
        "cl_border": "#3A2525",
        "bacground_img": "school/bg-card-ecommerce.png",
        "background_full": "school/ecommerce_fl.png",
        "bg_acad": "school/bg-acad-ecommerce.png",
        "bg_btns": "school/bg-btns-menu-ecommerce.png",
        "bg_calendar": "school/bg-calendar-ecommerce.png",
        "bg_educ": "school/bg-educ-ecommerce.png",
        "bg_live": "school/bg-live-ecommerce.png",
        "bg_commun": "school/bg-modu-commun-ecommerce.png",
        "bg_pro": "school/bg-pro-ecommerce.png",
        "bg_btn_follow": "school/bg-btn-follow-ec.png",
        "bg_btn_send": "school/bg-btn-send-ec.png",
        "bg_carrousel": "school/bg-btns-carrousel-ec.png",
        "bg_comment_edu": "school/bg-comment-educator-ec.png",
        "bg_favorite_video": "school/bg-favorite-videos-ec.png",
        "bg_stream_chat": "school/bg-stream-chat-ec.png",
        "bg_comment_preg": "school/bg-comment-ec.png",
        "bg_progress": "school/bg-progress-ec.png",
        "bg_send_preg": "school/btn-send-ec.png",
        "bg_btn_tap": "school/tab-ecommerce.png",
        "cl_text": "#fff",
        "created_at": "2024-01-18T11:50:21.747Z",
        "state": "A"
    },
    {
        "id": "a15451b5-7176-4998-a22d-235e9183ba8d",
        "title": "Personal development",
        "image": "school/p_dev.png",
        "color": "#8C64B3",
        "cl_backg": "#0C060E",
        "cl_border": "#3B1847",
        "bacground_img": "school/bg-card-personal.png",
        "background_full": "school/personaldevelopmet_fl.png",
        "bg_acad": "school/bg-acad-personal.png",
        "bg_btns": "school/bg-btns-menu-personal.png",
        "bg_calendar": "school/bg-calendar-personal.png",
        "bg_educ": "school/bg-educ-personal.png",
        "bg_live": "school/bg-live-personal.png",
        "bg_commun": "school/bg-modu-commun-personal.png",
        "bg_pro": "school/bg-pro-personal.png",
        "bg_btn_follow": "school/bg-btn-follow-pd.png",
        "bg_btn_send": "school/bg-btn-send-pd.png",
        "bg_carrousel": "school/bg-btns-carrousel-pd.png",
        "bg_comment_edu": "school/bg-comment-educator-pd.png",
        "bg_favorite_video": "school/bg-favorite-videos-pd.png",
        "bg_stream_chat": "school/bg-stream-chat-pd.png",
        "bg_comment_preg": "school/bg-comment-pd.png",
        "bg_progress": "school/bg-progress-pd.png",
        "bg_send_preg": "school/btn_send-pd.png",
        "bg_btn_tap": "school/tab-personal.png",
        "cl_text": "#fff",
        "created_at": "2024-01-18T11:50:21.856Z",
        "state": "A"
    },
    {
        "id": "f9df2ad9-dbc1-4592-af89-2f48db9f0df5",
        "title": "Social media",
        "image": "school/logo-social-media.png",
        "color": "#48CCFA",
        "cl_backg": "#05141A",
        "cl_border": "#26363C",
        "bacground_img": "school/bg-card-social-m.png",
        "background_full": "school/bg-card-social-m.png",
        "bg_acad": "school/bg-acad-social.png",
        "bg_btns": "school/bg-btns-menu-social.png",
        "bg_calendar": "school/bg-calendar-social.png",
        "bg_educ": "school/bg-educ-social.png",
        "bg_live": "school/bg-live-social.png",
        "bg_commun": "school/bg-modu-commun-social.png",
        "bg_pro": "school/bg-pro-social.png",
        "bg_btn_follow": "school/bg-btn-follow-sm.png",
        "bg_btn_send": "school/bg-btn-send-sm.png",
        "bg_carrousel": "school/bg-btns-carrousel-sm.png",
        "bg_comment_edu": "school/bg-comment.png",
        "bg_favorite_video": "school/bg-favorite-videos-sm.png",
        "bg_stream_chat": "school/bg-stream-chat-sm.png",
        "bg_comment_preg": "school/bg-comment-sm.png",
        "bg_progress": "school/bg-progress-sm.png",
        "bg_send_preg": "school/btn-send-sm.png",
        "bg_btn_tap": "school/tab-social.png",
        "cl_text": "#05141A",
        "created_at": "2024-02-11T13:34:49.422Z",
        "state": "A"
    },
    {
        "id": "0dd8daf2-b4fd-4cf3-8000-7c4810f411b5",
        "title": "Travel life & experiences",
        "image": "school/travel.png",
        "color": "#ff5100",
        "cl_backg": "#ff5100",
        "cl_border": "#ff5100",
        "bacground_img": "school/bg-card-travel.jpg",
        "background_full": "default.png",
        "bg_acad": "",
        "bg_btns": "",
        "bg_calendar": "",
        "bg_educ": "",
        "bg_live": "",
        "bg_commun": "",
        "bg_pro": "",
        "bg_btn_follow": "",
        "bg_btn_send": "",
        "bg_carrousel": "",
        "bg_comment_edu": "",
        "bg_favorite_video": "",
        "bg_stream_chat": "",
        "bg_comment_preg": "",
        "bg_progress": "",
        "bg_send_preg": "",
        "bg_btn_tap": "",
        "cl_text": "#fff",
        "created_at": "2024-05-07T16:05:40.557Z",
        "state": "A"
    }
]